### ISSUE TITLE
Document writing to files

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scippnexus#104]
https://scipp.github.io/scippnexus/user-guide/application-definitions.html#Writing-files explains the "advanced" method, but we lacks docs for the pedestrian way.

**Comment by jokasimr** [comment]
What is the "pedestrian way"? Directly using `h5py` or something in-between?

**Comment by SimonHeybrock** [comment]
`Group.__setitem__`, `create_field` and `create_class`. It is probably best to look in the unit tests, there are many examples.

Note also #222 which I just discovered while looking for this.
