### ISSUE TITLE
Deprecation warning with Python 3.12 

### ISSUE THREAD

**Issue by YooSunYoung** [scipp/scippnexus#195]
I wanted to test python 3.12 for other packages,
then I found out ``scippnexus`` was using ``dateutil.parser`` which throws DeprecationWarning in python 3.12.

But in the copier answer says it supports up to python 3.12
so I was wondering if it was tested with python 3.12 and I should just pin some dependencies...

**Comment by SimonHeybrock** [comment]
To be clear, are you saying that ScippNexus is not working, or is it simply causing a deprecation warning?

**Comment by YooSunYoung** [comment]
> To be clear, are you saying that ScippNexus is not working, or is it simply causing a deprecation warning?

It works, but it causes deprecation warning...! I'll update the title to be more clear.

**Comment by MridulS** [comment]
I think this is fixed upstream https://github.com/dateutil/dateutil/issues/1314

**Comment by MridulS** [comment]
I think we can use https://docs.python.org/3/library/datetime.html#datetime.datetime.fromisoformat directly? One less dependency?
