### ISSUE TITLE
Repeated forward slashes become absolute paths

### ISSUE THREAD

**Issue by g5t** [scipp/scippnexus#208]
Following up on #204 and the fix in #205, I noticed that a path with repeated forward slashes will silently ignore any valid path before the last such `'/'` and treat the rest of the path specification as an absolute path. E.g., a NeXus HDF5 file with an `NXinstrument` group at `/entry/instrument` opened as `file` will pass the following assert statement

```python
assert id(file['/entry/instrument']) == id(file['/entry//entry/instrument'])
```

this behavior is contrary to file system paths under [unix-like systems which treat repeated path separators as if they were singular](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_271).

**Comment by MridulS** [comment]
Maybe we can use `pathlib` to santize these things? I know they aren't path objects, but it should take care of all these corner cases.

**Comment by jl-wynen** [comment]
Yes:
```python
PurePosixPath('/entry//entry/instrument').as_posix()
```
Also takes care of the final slash
