### ISSUE TITLE
Docstring of `Group` methods/properties (and others?) don't show in docs

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scippnexus#222]
Compare https://scipp.github.io/scippnexus/generated/classes/scippnexus.Group.html to `Group` in https://github.com/scipp/scippnexus/blob/main/src/scippnexus/base.py. Why is no member documentation shown for this class?

**Comment by jokasimr** [comment]
Older scippnexus releases have the same problem, checked back to version 23.11, before that we didn't store the docs build in the release artifacts. So it seems the issue is not because of some recent change.
