### ISSUE TITLE
Docs workflow

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scippnexus#31]
See #30 and recent actions.

This is almost good to let us publish or update docs. One remaining subtlety:

- If we make docs of an old branch, e.g., old tag, we may want to use an old package. So we should extend this to not simply take a `publish` flag, but a version number? Then this can be used to:
  1. Get correct PyPI package (or use local one if `dev` is specified).
  2. Publish to correct folder (including version tag).
  
  This would also need to be able to handle extra folders, and specifying 'latest', to just use latest package (and publish into root).

**Comment by SimonHeybrock** [comment]
After a lot of back and forth, here is my "plan":

- Have one subfolder per non-patch version, i.e., `1.2` not `1.2.3`. Patches will overwrite.
- We want to have a banner indicating that a version is old. `sphinx-book-theme` now has an `'announcement'` option that can do this. I tried this locally and it works nicely. Implications:
  - We need to update `sphinx-book-theme`, which breaks our current custom header menus. Need to fix that.
  - When we make a new (non-patch) release, we rebuilt the previous "latest" with a banner and publish it in `x.y`.
  - New docs is published in root folder, as before.

As adding a new `release/x.y` folder anyway requires adding a new entry in the dropdown menu, we have a manual process anyway.

- Can we just run the workflow to build those docs by hand then?
- Should we remove the version select menu in the `release/x.y` docs? They only ever point to even-older versions, so this is not useful. With the banner linking to the latest version it seems unnecessary?

**Comment by jl-wynen** [comment]
How would this workflow be used? Do we have to specify any versions or destination folders? Do we have to remember to re-build the old release or can the be automated?

Re-building the old release requires getting the same packages and versions as before. Are we confident that our version pinning allows that? (Including conda and software on the GH action runner)

**Comment by SimonHeybrock** [comment]
> Re-building the old release requires getting the same packages and versions as before. Are we confident that our version pinning allows that? (Including conda and software on the GH action runner)

If it wouldn't work it would imply that we cannot make patch releases for older versions either, right? So the docs would only be a secondary problem?

**Comment by jl-wynen** [comment]
> > Re-building the old release requires getting the same packages and versions as before. Are we confident that our version pinning allows that? (Including conda and software on the GH action runner)
> 
> If it wouldn't work it would imply that we cannot make patch releases for older versions either, right? So the docs would only be a secondary problem?

True.
